#version: "3.8"
#
#services:
#  mysql_db:
#    image: mysql:8
#    container_name: mysql_db
#    ports:
#      - "3307:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root1234
#      MYSQL_DATABASE: library_management_db
#    volumes:
#      - ./mysql_data:/var/lib/mysql
#    networks:
#      - app-network
#
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: phpmyadmin
#    ports:
#      - "8081:80"
#    environment:
#
#      PMA_HOST: mysql_db
#      PMA_PORT: 3306
#      PMA_USER: root
#      MYSQL_ROOT_PASSWORD: root1234
#
#    depends_on:
#      - mysql_db
#
#  springboot:
#    build: .
#    container_name: library_management_SpringBoot_project
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/library_management_db
#      MYSQL_HOST: mysql
#      MYSQL_PORT: 3306
#      MYSQL_DB: library_management_db
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root1234
#    ports:
#      - "8082:8080"
#    depends_on:
#      - mysql_db
#    networks:
#      - app-network
#
#networks:
#  app-network:
#    driver: bridge
#
#
#volumes:
#  mysql_data: { }




version: "3.8"
services:
  springboot-app:
    image: springboot-app
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/library_management_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Anuj@1234
    depends_on:
      - mysqldb
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: Anuj@1234

    depends_on:
      - mysqldb
    networks:
      - app-network

  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: library_management_db
      MYSQL_ROOT_PASSWORD: Anuj@1234
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: