name: Spring Boot CI/CD

on:
  push:
    branches: [ main, beta, gamma ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

#    services:
#      mysqldb:
#        image: mysql:8.0
#        env:
#          MYSQL_DATABASE: library_management_db
#          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
#        ports:
#          - 3306:3306
#        options: >-
#          --health-cmd="mysqladmin ping"
#          --health-interval=10s
#          --health-timeout=5s
#          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven (Skip Tests)
        run: mvn -B package -DskipTests

      - name: Run Tests with JaCoCo
        run: mvn test jacoco:report
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/library_management_db
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
      
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: anujconsultadd/java_springboot_librarymanagement
          tags: v1, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
